script: "bundle install && bundle exec rake spec:all"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ruby-head

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  fast_finish: true
